export const fineFindPages = {
  dashboard: '/dashboard',
  manageMedia: '/dashboard/manage',
  manageProfile: '/dashboard/profile',
  login: '/login',
  forgotPassword: '/reset-password',
  signUp: '/signUp',
  products: '/dashboard/products',
  collections: '/dashboard/collections',
  createCollections: '/dashboard/collections/create',
  orders: '/dashboard/orders',
  onboarding: '/onboarding',
  admin: '/admin',
  requests: '/admin/requests',
  designerRequests: '/dashboard/requests',
};

export const fineFindApis = {
  instagramMe: '/api/instagram/v1/me',
  instagramMedia: '/api/instagram/v1/media',
  createShopifyPage: '/api/createPage',
  createInstagramAccount: 'api/user/v1/instagram-account',
  searchProducts: '/api/shopify/v1/products',
  sendEmail: '/api/email/sendEmail',
  submitApplication: '/api/apply/submitApplication',
  approveApplication: '/api/apply/approveApplication',
  checkApplication: '/api/apply/checkApplication',
  migrateApplication: '/api/apply/migrateApplication',
  createDesignerPage: '/api/shopify/v1/designer',
  sendRequestedProductsEmail: '/api/email/requestedProductsEmail',
  createDesignProduct: '/api/shopify/v1/product',
  requestedProductDenied: '/api/email/productDeniedEmail',
};
